# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: David Isaac De la Cruz Castillo
title: Desarrollador de aplicaciones y soluciones de Software.
email: dviddlccastillo@gmail.com
website: github.com/DvidCastill0/DvidCastill0.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  DvidCastill0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: David.DeLaCruzCastillo
# flickr_username: jekyll
instagram_username: davidisaacdlcc
linkedin_username: dvidcastillo
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: davidisaacdelacruzcastillo331
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ¡Hola!, soy David y actualmente soy estudiante de la Universidad de Guadalajara en la carrera de Licenciatura en Ingeniería en Computación. Siendoa demas egresado de la carrera de Tecnólogo Profesional en Sistemas Informáticos de la Escuela Politécnica de Guadalajara. Ocacionalmente realizo proyectos independientes para mejorar mis habilidades en la programación, asisto a eventos sobre tecnologia para aprender sobre las tendencias y me gusta dar soluciones en software a problemas que se me presentan.

  Mi principal habilidad actualmente es: <mark>ASP</mark>, <mark>PHP</mark>   and <mark>Java</mark>

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Decodificador Ensamblador para MIPS en Verilog
        link: github.com/DvidCastill0/
        # link_text: Project Website
        additional_links:
          - title:  DvidCastill0/DecodificadorMIPS
            icon: fab fa-github
            url: github.com/DvidCastill0/DecodificadorMIPS
          - title2: Acceso desde servidor alojado
            icon: fa-solid fa-eye
            url: https://dvidcastillo.000webhostapp.com/DecodificadorMIPS/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Este es uno de los mejores proyectos para entender como funciona el lenguaje maquina.
        description: | # this will include new lines to allow paragraphs
          Comence este proyecto como un aficionado para saber como lee la maquina 1s y 0s a partir del lenguaje ensamblador, el cual alavez me sirvio para poder meter instrucciones simples en una simulación de un procesador realizada en Verilog, esto a su vez fue una introducción para mi en el mundo de la arquitectura de computadoras, y vi conceptos basicos que necesita un editor de texto para señalar errores entre otras cosas, me hizo sentir muy orgulloso y se los comparto.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZOLTEK
        link: zoltek.com
        # link_text: boringcompany.com
        sub_title: Desarrollador full stack
        caption: Febrero 2022 - Actualidad
        quote: >
          Resolver los problemas relacionados a sistemas informaticos para administrar la calidad de la producción de un producto tan complejo como la fibra de carbono.
        description: | # this will include new lines to allow paragraphs
            Toda empresa necesita un desarrollador que comprenda los procesos en los cuales existe una rea de oportunidad de mejorar mediante sistemas informaticos, y ZOLTEK no es la excepción, aqui me he permitido desenvolver como desarrollador Full Stack para proyectos en el area de aseguramiento de calidad
              - Desarrollo en ASP.NET
              - RESTful API
              - RDLC
              - SQL Server
              - Frontend(HTML, CSS, JavaScript y JQuery)
              - Backend(C#)
              - Extracción y análisis de datos.
              - Digitalizacion de documentos
              - Firma electronica en documentos.
            Proyectos:
              - Creacion de sistema para realizar un llenado de datos filtrados desde bases de datos SQL y archivos Excel con la capacidad de ajuste de parametros, asi como su manejo y exportacion a distintos formatos por medio de RDLC.
              - Digitalizacion de documento para Reportes de Material no conforme, el cual permite realizar el llenado de datos de forma digital, asi como su firmado y adjuncion de evidencias para su posterior consulta. Ademas permitiendo el envio de correos automatico para cada fase y la impresion de reportes.
              - Sistema para seguimiento y control de workstations, con correo automatizado e impresion de reportes.

      - layout: left
        title: Ecoturismo Integrando Equipos S.A. de C.V.
        link: ecotours.com.mx
        # link_text: boringcompany.com
        sub_title: Desarrollador full stack
        caption: Enero 2020 - Febrero 2022
        quote: >
          Crear una herramienta que permita vivir la experiencia del Ecoturismo a la palma de tu mano.
        description: | # this will include new lines to allow paragraphs
            En este espacio tuve la oportunidad de desarrollar aun mas mis habilidades como programador de aplicaciones moviles, esta vez desarrollando una herramienta inteligente para realizar viajes de ecoturismo con una aplicación que funcionara como guia turistico, asi como administrar una gran base de datos NoSQL para este fin, los proyectos en el area de Turismo desarollados me reforzaron mis habilidades en:
              - Desarrollo en Android Studio
              - Java
              - Kotlin
              - Firebase
              - SQLite
              -Jetpack
              - Extracción y análisis de datos.
              - Compras integradas
              - AsyncTask.
              - GoogleMaps API
              - Geolocation
              Proyectos:
              - Creacion de un sistema para la actualizacion continuea de la base de datos de la empresa.
              - Creacion de una aplicacion que funciona como un guia digital con viajes digitales a un costo accesible, para android.
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2020 - Actual
        sub_title: Ingenieria en Computación
        quote: >
          La Universidad de Guadalajara (UdeG)​ es una institución pública de educación media-superior y superior que tiene su sede en la Zona Metropolitana de Guadalajara. Cronológicamente, de acuerdo a su fundación, es la segunda Universidad más antigua de México, la séptima de América del Norte y la decimocuarta de América Latina.
        description: | # this will include new lines to allow paragraphs
          Durante mis estudios en la universidad desarrolle la mayoria de mis conocimientos en programación, bases de datos, ciberseguridad, administración de redes y servidores y arquitectura de servidores, entusiasmandome por todo, decidi comenzar a enfocarme en el area de desarollo, la cual me encanta.
  - title: Un poco mas acerca de mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Ademas de mis intereses profesionales, tengo algunas aficiones que me gustaria compartir con ustedes
      - Senderismo
      - Gaming
      - Creación de contenido para youtube.
      - Historia de México y el mundo

      Miren esta imagen de uno de mis videojuegos favoritos con una genial historia que nos hace soñar con que no estamos solos en este universo:
      ![Humanidad](/images/halo.jpg "Humanidad")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
